DROP VIEW public.items_owner_dto;
DROP TABLE IF EXISTS public.comments;
DROP TABLE IF EXISTS public.bookings;
DROP TABLE IF EXISTS public.requests;
DROP TABLE IF EXISTS public.items;
DROP TABLE IF EXISTS public.users;

-- Table: public.users

CREATE TABLE IF NOT EXISTS public.users
(
    id    bigint                 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name  character varying(255) NOT NULL,
    email character varying(512) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

COMMENT ON TABLE public.users
    IS 'Таблица для хранения пользователей';

-- Table: public.items

CREATE TABLE IF NOT EXISTS public.items
(
    id           bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name         character varying(255),
    description  character varying(512),
    is_available boolean,
    owner_id     bigint,
    request_id   bigint,
    CONSTRAINT items_pkey PRIMARY KEY (id),
    CONSTRAINT owner_fkey FOREIGN KEY (owner_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Table: public.requests

CREATE TABLE IF NOT EXISTS public.requests
(
    id           bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description  character varying(512),
    requestor_id bigint,
    CONSTRAINT requests_pkey PRIMARY KEY (id),
    CONSTRAINT requestor_fkey FOREIGN KEY (requestor_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- Table: public.bookings

CREATE TABLE IF NOT EXISTS public.bookings
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    start_date timestamp without time zone,
    end_date   timestamp without time zone,
    item_id    bigint,
    booker_id  bigint,
    status     character varying(30),
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    CONSTRAINT booker_fkey FOREIGN KEY (booker_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT item_fkey FOREIGN KEY (item_id)
        REFERENCES public.items (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- Table: public.comments

CREATE TABLE IF NOT EXISTS public.comments
(
    id           bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    text         character varying           NOT NULL,
    item_id      bigint                      NOT NULL,
    author_id    bigint                      NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT author_fkey FOREIGN KEY (author_id)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT item_fkey FOREIGN KEY (item_id)
        REFERENCES public.items (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- View: public.items_owner_dto

CREATE OR REPLACE VIEW public.items_owner_dto
AS
SELECT b.id,
       b.name,
       b.description,
       b.is_available,
       b.owner_id,
       lb.lastbooking,
       nb.nextbooking
FROM items b
         LEFT JOIN (SELECT bookings.item_id,
                           max(bookings.end_date) AS lastbooking
                    FROM bookings
                    WHERE bookings.start_date < current_date
                      AND bookings.status::text = 'APPROVED'::text
                    GROUP BY bookings.item_id) lb ON b.id = lb.item_id
         LEFT JOIN (SELECT bookings.item_id,
                           min(bookings.start_date) AS nextbooking
                    FROM bookings
                    WHERE bookings.start_date > now()
                      AND (bookings.status::text = ANY
                           (ARRAY ['APPROVED'::character varying, 'WAITING'::character varying]::text[]))
                    GROUP BY bookings.item_id) nb ON b.id = nb.item_id
ORDER BY b.id;